# Generated by Django 4.1.3 on 2022-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_collumn_seat_column_session_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone',
        ),
    ]
