# Generated by Django 4.1.3 on 2022-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
