# Generated by Django 4.1.3 on 2022-12-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_session_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'column')},
        ),
    ]
