# Generated by Django 4.1.3 on 2022-12-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_collumn_seat_column_session_pricing'),
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='session',
            name='room',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.session'),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
