# Generated by Django 4.1.3 on 2022-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_session_movie_remove_session_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
