# Generated by Django 4.1.3 on 2022-12-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_session_date'),
        ('booking', '0005_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='count',
        ),
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Children'), (2, 'Student'), (3, 'Adult')])),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.seat')),
            ],
        ),
    ]
