# Generated by Django 4.1.3 on 2022-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_ticket_count_bookticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='bookticket',
            name='column',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookticket',
            name='row',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
