# Generated by Django 4.1.3 on 2022-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_bookticket_seat_bookticket_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='4169787845455656', help_text='Enter Credit Card', max_length=16),
            preserve_default=False,
        ),
    ]
