# Generated by Django 4.1.3 on 2022-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_order_paid_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(help_text='Enter Credit Card', max_length=16, null=True),
        ),
    ]
