# Generated by Django 4.1.3 on 2022-12-06 08:22

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
